In [2]:
import pandas as pd
# Reading dataset
data_path = 'new_linguistic_data.csv'
df = pd.read_csv(data_path, error_bad_lines=False)

<ipython-input-2-d124644aaf23>:4: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(data_path, error_bad_lines=False)


In [3]:
df.head()

Unnamed: 0                                               Body   Label  \
0           0  Karadeniz için tiyatro festivali zamanı!  Devl...  gerçek   
1           1  Sözde Torbacının Haklı Gururu Dün gece 02 sula...   yalan   
2           2  Buse'yi aramak için 400 bin liralık cihazını a...  gerçek   
3           3  West Ham 3-0 Southampton (MAÇ ÖZET)  Premier L...  gerçek   
4           4  AK Partili Yavuz duyurdu: YSK'ya ek dilekçe ve...  gerçek   

   character_count  word_count  letter_count  \
0             3691         476          2948   
1              875         115           726   
2              360          47           301   
3              214          34           163   
4             1105         143           925   

   total_number_of_upper_characters  total_number_of_lower_characters  \
0                               245                              2703   
1                                37                               689   
2                                12                               289   
3                                15                               148   
4                                53                               872   

   number_of_special_character  short_words  ...  MONEY  NORP  ORDINAL  ORG  \
0                           71          125  ...      0     2        0   16   
1                           27           28  ...      0     1        0    6   
2                            5           10  ...      0     0        0    2   
3                            9           14  ...      0     0        0    2   
4                           33           40  ...      0     1        0    6   

   PERCENT  PERSON  PRODUCT  QUANTITY  TIME  WORK_OF_ART  
0        0      61       11         0     0            0  
1        0      14        0         2     0            0  
2        0       6        0         0     0            0  
3        0       2        0         0     0            0  
4        0      15        0         0     0            1  

[5 rows x 41 columns]

In [4]:
df['Label'] = df['Label'].replace({'yalan': 0, 'gerçek': 1})
df["sentiment"].replace({"positive": 1, "negative": 0}, inplace=True)

In [5]:
df.head()

Unnamed: 0                                               Body  Label  \
0           0  Karadeniz için tiyatro festivali zamanı!  Devl...      1   
1           1  Sözde Torbacının Haklı Gururu Dün gece 02 sula...      0   
2           2  Buse'yi aramak için 400 bin liralık cihazını a...      1   
3           3  West Ham 3-0 Southampton (MAÇ ÖZET)  Premier L...      1   
4           4  AK Partili Yavuz duyurdu: YSK'ya ek dilekçe ve...      1   

   character_count  word_count  letter_count  \
0             3691         476          2948   
1              875         115           726   
2              360          47           301   
3              214          34           163   
4             1105         143           925   

   total_number_of_upper_characters  total_number_of_lower_characters  \
0                               245                              2703   
1                                37                               689   
2                                12                               289   
3                                15                               148   
4                                53                               872   

   number_of_special_character  short_words  ...  MONEY  NORP  ORDINAL  ORG  \
0                           71          125  ...      0     2        0   16   
1                           27           28  ...      0     1        0    6   
2                            5           10  ...      0     0        0    2   
3                            9           14  ...      0     0        0    2   
4                           33           40  ...      0     1        0    6   

   PERCENT  PERSON  PRODUCT  QUANTITY  TIME  WORK_OF_ART  
0        0      61       11         0     0            0  
1        0      14        0         2     0            0  
2        0       6        0         0     0            0  
3        0       2        0         0     0            0  
4        0      15        0         0     0            1  

[5 rows x 41 columns]

In [7]:
df["sentiment"]

0       1
1       0
2       1
3       0
4       1
       ..
4450    0
4451    1
4452    0
4453    0
4454    1
Name: sentiment, Length: 4455, dtype: int64

In [8]:
features = ["character_count", "word_count", "letter_count",
                      "total_number_of_upper_characters", "total_number_of_lower_characters",
                      "number_of_special_character", "short_words", "long_words", "number_of_different_words","unique_word_types_count"
                      ,"verb_count","adjective_count","determiners_count","conjunction_count","noun_count",
                      "adverb_count","preposition_count","pronoun_count",
                      "number_count","sentiment","CARDINAL","DATE","EVENT","FAC","GPE",
            "LANGUAGE","LAW","LOC","MONEY","NORP","ORDINAL","ORG","PERCENT","PERSON","PRODUCT","QUANTITY","TIME","WORK_OF_ART"]
target = ['Label']

X = df[features].values
y = df[target].values

In [9]:
#df.head()

**LOGISTIC REGRESSİON**


In [10]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
import numpy as np

best_features = SelectFromModel(LogisticRegression())
best_features.fit(X, y)

transformedX = best_features.transform(X)
print(f"Old Shape: {X.shape}, New shape: {transformedX.shape}")
print("Selected features: ", best_features.get_support())
print("Selected features: ", np.array(features)[best_features.get_support(indices=True)])

Old Shape: (4455, 38), New shape: (4455, 11)
Selected features:  [ True False  True False False False False False  True  True False False
  True  True False  True  True False  True False False False False False
 False False False False False False False  True False  True False False
 False False]
Selected features:  ['character_count' 'letter_count' 'number_of_different_words'
 'unique_word_types_count' 'determiners_count' 'conjunction_count'
 'adverb_count' 'preposition_count' 'number_count' 'ORG' 'PERSON']


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
#transformedX[:5]

%30 test - %70 train

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.3)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')


print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.9244577412116679
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.91      0.92       649
           1       0.92      0.93      0.93       688

    accuracy                           0.92      1337
   macro avg       0.92      0.92      0.92      1337
weighted avg       0.92      0.92      0.92      1337

Confussion matrix: 
[[593  56]
 [ 45 643]]

Accuracy: 0.9244577412116679
Precision: 0.9245365720810615
Recall: 0.9244577412116679
F1 score: 0.924434465785153


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


%20 test %80 train

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')


print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.9135802469135802
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.91      0.91       427
           1       0.92      0.91      0.92       464

    accuracy                           0.91       891
   macro avg       0.91      0.91      0.91       891
weighted avg       0.91      0.91      0.91       891

Confussion matrix: 
[[390  37]
 [ 40 424]]

Accuracy: 0.9135802469135802
Precision: 0.9136232198163624
Recall: 0.9135802469135802
F1 score: 0.9135913665513044


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


**DECISION TREE CLASSIFIER**

In [14]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.feature_selection import SelectFromModel

import numpy as np

best_features = SelectFromModel(DecisionTreeClassifier())
best_features.fit(X, y)

transformedX = best_features.transform(X)
print(f"Old Shape: {X.shape}, New shape: {transformedX.shape}")
print("Selected features: ", best_features.get_support())
print("Selected features: ", np.array(features)[best_features.get_support(indices=True)])

Old Shape: (4455, 38), New shape: (4455, 6)
Selected features:  [False False False  True False False False False  True  True False False
 False  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False]
Selected features:  ['total_number_of_upper_characters' 'number_of_different_words'
 'unique_word_types_count' 'conjunction_count' 'noun_count' 'adverb_count']


In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.3)

model = (DecisionTreeClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.8324607329842932
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.83      0.83       672
           1       0.83      0.84      0.83       665

    accuracy                           0.83      1337
   macro avg       0.83      0.83      0.83      1337
weighted avg       0.83      0.83      0.83      1337

Confussion matrix: 
[[555 117]
 [107 558]]

Accuracy: 0.8324607329842932
Precision: 0.8325482566446802
Recall: 0.8324607329842932
F1 score: 0.8324579212308357


In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)

model = (DecisionTreeClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.8439955106621774
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.83      0.84       440
           1       0.84      0.85      0.85       451

    accuracy                           0.84       891
   macro avg       0.84      0.84      0.84       891
weighted avg       0.84      0.84      0.84       891

Confussion matrix: 
[[367  73]
 [ 66 385]]

Accuracy: 0.8439955106621774
Precision: 0.8440502198969411
Recall: 0.8439955106621774
F1 score: 0.8439707404621078


**LinearSVC**

In [17]:
from sklearn.svm import LinearSVC

from sklearn.feature_selection import SelectFromModel

import numpy as np

best_features = SelectFromModel(LinearSVC())
best_features.fit(X, y)

transformedX = best_features.transform(X)
print(f"Old Shape: {X.shape}, New shape: {transformedX.shape}")
print("Selected features: ", best_features.get_support())
print("Selected features: ", np.array(features)[best_features.get_support(indices=True)])


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Old Shape: (4455, 38), New shape: (4455, 14)
Selected features:  [ True False  True False False False False False  True  True False False
  True  True False  True  True  True  True  True  True False False False
  True False False False False  True False False False False False False
 False False]
Selected features:  ['character_count' 'letter_count' 'number_of_different_words'
 'unique_word_types_count' 'determiners_count' 'conjunction_count'
 'adverb_count' 'preposition_count' 'pronoun_count' 'number_count'
 'sentiment' 'CARDINAL' 'GPE' 'NORP']


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.3)

model = (LinearSVC())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.8803290949887809
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.78      0.86       639
           1       0.83      0.97      0.89       698

    accuracy                           0.88      1337
   macro avg       0.89      0.88      0.88      1337
weighted avg       0.89      0.88      0.88      1337

Confussion matrix: 
[[501 138]
 [ 22 676]]

Accuracy: 0.8803290949887809
Precision: 0.8913884117852364
Recall: 0.8803290949887809
F1 score: 0.8789463990282224


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)

model = (LinearSVC())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.819304152637486
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.98      0.84       433
           1       0.98      0.66      0.79       458

    accuracy                           0.82       891
   macro avg       0.86      0.82      0.82       891
weighted avg       0.86      0.82      0.82       891

Confussion matrix: 
[[426   7]
 [154 304]]

Accuracy: 0.819304152637486
Precision: 0.8593965800344926
Recall: 0.819304152637486
F1 score: 0.8151441888294104


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Random Forest


In [20]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.feature_selection import SelectFromModel

import numpy as np

best_features = SelectFromModel(RandomForestClassifier())
best_features.fit(X, y)

transformedX = best_features.transform(X)
print(f"Old Shape: {X.shape}, New shape: {transformedX.shape}")
print("Selected features: ", best_features.get_support())
print("Selected features: ", np.array(features)[best_features.get_support(indices=True)])


/usr/local/lib/python3.10/dist-packages/sklearn/feature_selection/_from_model.py:357: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X, y, **fit_params)


Old Shape: (4455, 38), New shape: (4455, 12)
Selected features:  [False False  True  True  True False False False  True  True  True  True
 False  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False]
Selected features:  ['letter_count' 'total_number_of_upper_characters'
 'total_number_of_lower_characters' 'number_of_different_words'
 'unique_word_types_count' 'verb_count' 'adjective_count'
 'conjunction_count' 'noun_count' 'adverb_count' 'preposition_count'
 'pronoun_count']


In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.3)

model = (RandomForestClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

<ipython-input-21-429aa1d00c2a>:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


Accuracy: 0.8975317875841436
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.89      0.90       663
           1       0.89      0.91      0.90       674

    accuracy                           0.90      1337
   macro avg       0.90      0.90      0.90      1337
weighted avg       0.90      0.90      0.90      1337

Confussion matrix: 
[[589  74]
 [ 63 611]]

Accuracy: 0.8975317875841436
Precision: 0.897625607877562
Recall: 0.8975317875841436
F1 score: 0.8975179117430926


In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)

model = (RandomForestClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

<ipython-input-22-72c2ccf04efa>:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


Accuracy: 0.9034792368125701
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.91      0.90       408
           1       0.92      0.90      0.91       483

    accuracy                           0.90       891
   macro avg       0.90      0.90      0.90       891
weighted avg       0.90      0.90      0.90       891

Confussion matrix: 
[[370  38]
 [ 48 435]]

Accuracy: 0.9034792368125701
Precision: 0.9038663778844038
Recall: 0.9034792368125701
F1 score: 0.9035586872265123


Gradient Boosting 

In [23]:
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.feature_selection import SelectFromModel

import numpy as np

best_features = SelectFromModel(GradientBoostingClassifier())
best_features.fit(X, y)

transformedX = best_features.transform(X)
print(f"Old Shape: {X.shape}, New shape: {transformedX.shape}")
print("Selected features: ", best_features.get_support())
print("Selected features: ", np.array(features)[best_features.get_support(indices=True)])


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Old Shape: (4455, 38), New shape: (4455, 6)
Selected features:  [False False False  True False False False False False  True False False
 False  True  True  True False False  True False False False False False
 False False False False False False False False False False False False
 False False]
Selected features:  ['total_number_of_upper_characters' 'unique_word_types_count'
 'conjunction_count' 'noun_count' 'adverb_count' 'number_count']


In [24]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.3)

model = (GradientBoostingClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.8885564697083022
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.88      0.89       659
           1       0.88      0.90      0.89       678

    accuracy                           0.89      1337
   macro avg       0.89      0.89      0.89      1337
weighted avg       0.89      0.89      0.89      1337

Confussion matrix: 
[[577  82]
 [ 67 611]]

Accuracy: 0.8885564697083022
Precision: 0.888716778435812
Recall: 0.8885564697083022
F1 score: 0.8885246538849464


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score,classification_report

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)

model = (GradientBoostingClassifier())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_predictions = model.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_predictions)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Confussion matrix: \n{conf_matrix}\n')

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.8832772166105499
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.87      0.88       445
           1       0.87      0.90      0.88       446

    accuracy                           0.88       891
   macro avg       0.88      0.88      0.88       891
weighted avg       0.88      0.88      0.88       891

Confussion matrix: 
[[387  58]
 [ 46 400]]

Accuracy: 0.8832772166105499
Precision: 0.8835519908700152
Recall: 0.8832772166105499
F1 score: 0.883254275349477
